# Generated by Django 4.0.6 on 2022-10-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_profile',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=b'I01\n', serialize=False)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=10)),
                ('bp', models.CharField(max_length=10)),
                ('pulse', models.CharField(max_length=10)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_app.patient_profile')),
            ],
        ),
        migrations.CreateModel(
            name='case_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.CharField(max_length=200)),
                ('dur', models.CharField(max_length=200)),
                ('rel', models.CharField(max_length=200)),
                ('fre', models.CharField(max_length=200)),
                ('asso', models.CharField(max_length=200)),
                ('loc', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=100)),
                ('onset', models.CharField(max_length=200)),
                ('pain', models.CharField(max_length=100)),
                ('p_medix', models.CharField(max_length=200)),
                ('e_f', models.CharField(max_length=100)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_app.patient_profile')),
            ],
        ),
    ]
